### ISSUE TITLE
v 0.35 多线程版本（main_dev.py）选择kaggle部署时报错

### ISSUE THREAD

**Issue by lusuon** [fkiliver/RPGMaker_LLM_Translator#25]
line 125的init方法内，未初始化变量 api_num，导致报错：

```
Traceback (most recent call last):
  File "~\main_dev.py", line 366, in <module>
    main()
  File "~\main_dev.py", line 291, in main
    init()
  File "~\main_dev.py", line 167, in init
    for i in range(api_num):
                   ^^^^^^^
UnboundLocalError: cannot access local variable 'api_num' where it is not associated with a value
```

个人的暂时解决方法：初始化该变量 api_num = 1

**Comment by fkiliver** [comment]
确实，kaggle没有添加多api支持，没有对api_num赋值。已修复
